### ISSUE TITLE
NoMethodError in constructor

### ISSUE THREAD

**Issue by 2016rshah** [akerl/githubchart#44]
Hey! The app had broken based on some updates to githubstats and I realized I was using githubchart 1.01 so I tried to update all the way to the latest version. However, I tried to use the constructor (updating it to be compatible with githubchart 2.1.0) like so:

```ruby
# username is a string
svg = GithubChart.new(user: username).render('svg')
```

and I got the following error

```
2017-09-29 13:02:31 - NoMethodError - undefined method `date' for nil:NilClass:
	/Users/rushi/.rvm/gems/ruby-2.2.1/gems/githubstats-1.4.0/lib/githubstats/data.rb:182:in `_pad'
	/Users/rushi/.rvm/gems/ruby-2.2.1/gems/githubstats-1.4.0/lib/githubstats/data.rb:173:in `pad'
	/Users/rushi/.rvm/gems/ruby-2.2.1/gems/githubchart-2.1.0/lib/githubchart.rb:79:in `matrix'
	/Users/rushi/.rvm/gems/ruby-2.2.1/gems/githubchart-2.1.0/lib/githubchart/svg.rb:18:in `render_svg'
	/Users/rushi/.rvm/gems/ruby-2.2.1/gems/githubchart-2.1.0/lib/githubchart.rb:69:in `render'
	app.rb:21:in `block in <main>'
```

Please let me know what I need to do to fix it!

**Comment by akerl** [comment]
Is it failing for specific usernames? I'm not able to reproduce:

```
❯ gem list | grep github
githubchart (2.1.0)
githubstats (1.4.0)
~ bean
❯ cat test.rb
require 'githubchart'

username = 'akerl'
svg = GithubChart.new(user: username).render('svg')
p svg.size

~ bean
❯ ruby test.rb
52424
```

I am on Ruby 2.4.2, I'm installing 2.2.1 now to test there.

**Comment by akerl** [comment]
Confirmed it works for me in 2.2.1 as well, but I do get the same error as you if I provide a bad username:

```
❯ cat test.rb
require 'githubchart'

username = 'akerlllllllll'
svg = GithubChart.new(user: username).render('svg')
p svg.size

~ bean
❯ ruby test.rb
/opt/asdf/installs/ruby/2.2.1/lib/ruby/gems/2.2.0/gems/githubstats-1.4.0/lib/githubstats/data.rb:182:in `_pad': undefined method `date' for nil:NilClass (NoMethodError)
	from /opt/asdf/installs/ruby/2.2.1/lib/ruby/gems/2.2.0/gems/githubstats-1.4.0/lib/githubstats/data.rb:173:in `pad'
	from /opt/asdf/installs/ruby/2.2.1/lib/ruby/gems/2.2.0/gems/githubchart-2.1.0/lib/githubchart.rb:79:in `matrix'
	from /opt/asdf/installs/ruby/2.2.1/lib/ruby/gems/2.2.0/gems/githubchart-2.1.0/lib/githubchart/svg.rb:18:in `render_svg'
	from /opt/asdf/installs/ruby/2.2.1/lib/ruby/gems/2.2.0/gems/githubchart-2.1.0/lib/githubchart.rb:69:in `render'
	from test.rb:4:in `<main>'
```

Looks like this is some bad validation: if the username is bad, the error should be more clear.

**Comment by 2016rshah** [comment]
Everything magically started working for me, too. Not sure what changed, maybe I was just passing in a bad username. I'll let you know if it comes up again, but either way, thanks for the quick response!

**Comment by akerl** [comment]
I also pushed 2.0.0 of githubstats and 3.0.0 of githubchart, which should return saner error messages if called w/ an invalid username. Before, I wasn't checking the HTTP response code from GitHub, which is why it failed late in the process with a hard-to-triage error.

**Comment by 2016rshah** [comment]
Hey, I haven't changed any code, but the [GithubchartAPI](https://github.com/2016rshah/githubchart-api) stopped working. When I checked what broke, I ran into this issue again. This is the error message:

```
NoMethodError - undefined method `date' for nil:NilClass:
	/Users/rushi/.rvm/gems/ruby-2.2.1/gems/githubstats-1.4.0/lib/githubstats/data.rb:182:in `_pad'
	/Users/rushi/.rvm/gems/ruby-2.2.1/gems/githubstats-1.4.0/lib/githubstats/data.rb:173:in `pad'
	/Users/rushi/.rvm/gems/ruby-2.2.1/gems/githubchart-2.1.0/lib/githubchart.rb:79:in `matrix'
	/Users/rushi/.rvm/gems/ruby-2.2.1/gems/githubchart-2.1.0/lib/githubchart/svg.rb:18:in `render_svg'
	/Users/rushi/.rvm/gems/ruby-2.2.1/gems/githubchart-2.1.0/lib/githubchart.rb:69:in `render'
	app.rb:21:in `block in <main>'
```

I am still on 2.0.0 of githubstats, so I tried to update to 3.0.0 like you mentioned. When I run `bundle install`, though, I get the following error:

```
Fetching gem metadata from http://rubygems.org/.........
Resolving dependencies...
Using basiccache 1.0.0
Using bundler 1.16.0
Fetching curb 0.9.11 (was 0.9.4)
Installing curb 0.9.11 (was 0.9.4) with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/rushi/.rvm/gems/ruby-2.2.1/gems/curb-0.9.11/ext
/Users/rushi/.rvm/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20210204-23389-1ut13ii.rb extconf.rb
checking for curl-config... yes
checking for curlopt_tcp_keepalive... yes
checking for curlopt_tcp_keepidle... yes
checking for curlopt_tcp_keepintvl... yes
checking for curlinfo_appconnect_time... yes
checking for curlinfo_redirect_time... yes
[...]
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for ruby/io.h... yes
checking for rb_io_stdio_file()... no
creating curb_config.h
creating Makefile

current directory: /Users/rushi/.rvm/gems/ruby-2.2.1/gems/curb-0.9.11/ext
make "DESTDIR=" clean

current directory: /Users/rushi/.rvm/gems/ruby-2.2.1/gems/curb-0.9.11/ext
make "DESTDIR="
compiling curb_easy.c
curb_easy.c:30:15: error: static declaration of 'rb_io_stdio_file' follows non-static declaration
static FILE * rb_io_stdio_file(rb_io_t *fptr) {
              ^
/Users/rushi/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/io.h:133:7: note: previous declaration is here
FILE *rb_io_stdio_file(rb_io_t *fptr);
      ^
curb_easy.c:31:16: error: no member named 'f' in 'struct rb_io_t'
  return fptr->f;
         ~~~~  ^
2 errors generated.
make: *** [curb_easy.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/rushi/.rvm/gems/ruby-2.2.1/gems/curb-0.9.11 for inspection.
Results logged to /Users/rushi/.rvm/gems/ruby-2.2.1/extensions/x86_64-darwin-14/2.2.0-static/curb-0.9.11/gem_make.out

An error occurred while installing curb (0.9.11), and Bundler cannot continue.
Make sure that `gem install curb -v '0.9.11'` succeeds before bundling.

In Gemfile:
  githubchart was resolved to 3.1.0, which depends on
    githubstats was resolved to 2.0.0, which depends on
      curb
```

I'm still on Ruby 2.2.1. Any words of wisdom on where I should go from here?

**Comment by akerl** [comment]
GitHubChart 3.2.0 was released in October of last year, and deps on GitHubStats 3.1.0. For the curb error, I wonder if you’re getting that because they’re expecting newer Ruby. Ruby 2.2.1 has been EOL’d for a while now: https://www.ruby-lang.org/en/downloads/

**Comment by 2016rshah** [comment]
Updated to ruby 2.6.6, which solved the curb error. Now I'm running githubchart 3.2.0, githubstats 3.1.0. The error now reads

```
RuntimeError - Failed loading data from GitHub: https://github.com/users/favicon.ico/contributions 404:
	/Users/rushi/.rvm/gems/ruby-2.6.6/gems/githubstats-3.1.0/lib/githubstats.rb:156:in `request'
	/Users/rushi/.rvm/gems/ruby-2.6.6/gems/githubstats-3.1.0/lib/githubstats.rb:144:in `download'
	/Users/rushi/.rvm/gems/ruby-2.6.6/gems/githubstats-3.1.0/lib/githubstats.rb:119:in `load_data'
	/Users/rushi/.rvm/gems/ruby-2.6.6/gems/githubstats-3.1.0/lib/githubstats.rb:92:in `data'
	/Users/rushi/.rvm/gems/ruby-2.6.6/gems/githubchart-3.2.0/lib/githubchart.rb:81:in `load_stats'
	/Users/rushi/.rvm/gems/ruby-2.6.6/gems/githubchart-3.2.0/lib/githubchart.rb:61:in `initialize'
	/Users/rushi/.rvm/gems/ruby-2.6.6/gems/githubchart-3.2.0/lib/githubchart.rb:12:in `new'
	/Users/rushi/.rvm/gems/ruby-2.6.6/gems/githubchart-3.2.0/lib/githubchart.rb:12:in `new'
	app.rb:21:in `block in <main>'
```

Seems like that should be `https://github.com/users/2016rshah/contributions` instead of `https://github.com/users/favicon.ico/contributions`, but not sure where the `favicon.ico` came from.

**Comment by 2016rshah** [comment]
I used the `test.rb` you mentioned above and these are the results I get:

```
$ ~/github/githubchart-api (master) cat test.rb
require 'githubchart'

username = 'akerl'
svg = GithubChart.new(user: username).render('svg')
p svg.size

$ ~/github/githubchart-api (master) gem list | grep github
githubchart (3.2.0)
githubstats (3.1.0)

$ ~/github/githubchart-api (master) ruby test.rb
Traceback (most recent call last):
	5: from test.rb:4:in `<main>'
	4: from /Users/rushi/.rvm/gems/ruby-2.6.6/gems/githubchart-3.2.0/lib/githubchart.rb:70:in `render'
	3: from /Users/rushi/.rvm/gems/ruby-2.6.6/gems/githubchart-3.2.0/lib/githubchart/svg.rb:22:in `render_svg'
	2: from /Users/rushi/.rvm/gems/ruby-2.6.6/gems/githubchart-3.2.0/lib/githubchart.rb:91:in `matrix'
	1: from /Users/rushi/.rvm/gems/ruby-2.6.6/gems/githubstats-3.1.0/lib/githubstats/data.rb:191:in `pad'
/Users/rushi/.rvm/gems/ruby-2.6.6/gems/githubstats-3.1.0/lib/githubstats/data.rb:200:in `_pad': undefined method `date' for nil:NilClass (NoMethodError)
```

**Comment by akerl** [comment]
Huh, that’s super weird. I’ll poke around and see if I can reproduce that

**Comment by akerl** [comment]
It looks like GitHub changed their CSS, for the contribution data page. 

https://github.com/akerl/githubstats/commit/8a2c91ce712f03182640ae00c989551fc0dfe100#diff-ca462fcf017e26b5efeb03d6d2ee91e663f7536779c9e18e2142c12a4823d68a

That should fix the issue. I’ve cut GitHubStats 3.2 and GitHubChart 3.3.1 which should resolve things.

**Comment by 2016rshah** [comment]
Beautiful, thank you so much for the prompt response!

I was confused for a second because my old code still wasn't working, until I realized the API changed from `GithubChart.new(user: username).svg` to `GithubChart.new(user: username).render('svg')` somewhere along the way 😅
